name: Dependabot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot
        uses: dependabot/dependabot-core@master
        with:
          config-path: ".dependabot/config.yml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
