name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Semgrep
        uses: returntocorp/semgrep-action@v1
      - name: Run Semgrep
        run: semgrep .

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  super-linter:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      VALIDATE_ALL_CODEBASE: false
      VALIDATE_ANSIBLE: false
      VALIDATE_ARM: false
      VALIDATE_BASH: true
      VALIDATE_CFN: false
      VALIDATE_CLOJURE: false
      VALIDATE_COFFEE: false
      VALIDATE_CS: false
      VALIDATE_CSS: true
      VALIDATE_DART: false
