name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Set up goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
      - name: Run goreleaser
        run: |
          goreleaser --rm-dist
          docker build -t taredkkhaldi/supercalculator:${{ github.ref }} .
          docker push taredkkhaldi/supercalculator:${{ github.ref }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
